/**
 * Emits the uploadable address SQL.
 *
 *   npm run seed:address:sql
 *
 * The hospital loads the national dataset by uploading the generated file in
 * phpMyAdmin, so it has to be a self-contained statement list rather than
 * something that only works through Prisma.
 *
 * Each level is its own table (`Division` -> `District` -> `Upazila` -> `Union`)
 * joined by real foreign keys, which shapes the file in two ways:
 *
 *   1. Rows are inserted top down (divisions first) so a child never precedes the
 *      parent it points at.
 *   2. Ids are written out as explicit literals. A plain `VALUES` list cannot look
 *      up the id a previous statement created, and phpMyAdmin runs each statement
 *      on its own, so this file assigns them itself. The tables are emptied first,
 *      so the ids are free, and the same dataset always produces the same ids.
 *
 * Branch ids are read from the database this script connects to and written in as
 * literals for the same reason: a plain VALUES list cannot select from `branch`.
 * That means the file only fits the branches that existed when it was generated: run
 * this against production after seeding, or the rows land on the wrong branch.
 * `npm run seed:address` has no such constraint and is the safer option when you
 * have shell access.
 *
 * The statements touch only the four address tables. Every other lookup list
 * (blood groups, visit types, payment methods, the manual areas/cities rows) is
 * app-owned and left untouched.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { PrismaClient } from "@prisma/client";
import { buildAddressRows, type AddressRow } from "./addressDataset";
import { ADDRESS_CATEGORY_ORDER } from "../src/lib/bangladeshAddress";
import { LOOKUP_SPECS, type MasterDataCategory } from "../src/lib/masterDataRegistry";

const OUT_FILE = join(import.meta.dirname, "..", "sql", "address-master-data.sql");

/** Keeps each INSERT well under MySQL's max_allowed_packet. */
const ROWS_PER_INSERT = 250;

const sqlString = (value: string | null): string => {
  if (value === null) return "NULL";
  return `'${value.replace(/\\/g, "\\\\").replace(/'/g, "''")}'`;
};

const sqlNumber = (value: number | null): string => (value === null ? "NULL" : String(value));

/**
 * The columns for one level, and how to build a VALUES tuple for it.
 *
 * `divisionId`/`districtId`/`upazilaId` sit right after `branchId` because the FK
 * parent is the only part of the tuple that depends on the level above.
 */
function tupleColumns(spec: (typeof LOOKUP_SPECS)[MasterDataCategory]): {
  columns: string;
  tuple: (row: AddressRow, branchId: number, parentId: number | null, id: number) => string;
} {
  const base = (extra: string) =>
    "  (`id`, `branchId`" +
    (extra ? `, \`${extra}\`` : "") +
    ", `name`, `code`" +
    (spec.hasBnName ? ", `bnName`" : "") +
    (spec.hasCoordinates ? ", `lat`, `lon`" : "") +
    (spec.address ? ", `url`" : "") +
    ", `sortOrder`, `status`, `createdAt`, `updatedAt`)";

  const values =
    (row: AddressRow, branchId: number, parentId: number | null, id: number) =>
      `    (${id}, ${branchId}` +
      (spec.parent ? `, ${parentId ?? "NULL"}` : "") +
      `, ${sqlString(row.label)}, ${sqlString(row.code)}` +
      (spec.hasBnName ? `, ${sqlString(row.bnName)}` : "") +
      (spec.hasCoordinates ? `, ${sqlNumber(row.lat)}, ${sqlNumber(row.lon)}` : "") +
      (spec.address ? `, ${sqlString(row.url)}` : "") +
      // `updatedAt` is Prisma-managed with no column default, so it is set
      // explicitly alongside `createdAt` rather than left to the app.
      `, ${row.sortOrder}, 'active', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3))`;

  return {
    columns: base(spec.parent?.field ?? ""),
    tuple: values,
  };
}

function buildSql(rows: AddressRow[], branchIds: number[]): string {
  const parts: string[] = [];

  parts.push("-- Bangladesh address data");
  parts.push("-- Generated by: npm run seed:address:sql");
  parts.push("-- Source:       prisma/address-source/{divisions,districts,upazilas,unions}.sql");
  parts.push("--");
  parts.push("-- Upload this file in phpMyAdmin to load the address hierarchy.");
  parts.push("-- It replaces the rows in the Division, District, Upazila and Union");
  parts.push("-- tables and replicates them across every branch. Every other lookup");
  parts.push("-- table is untouched.");
  parts.push("--");
  parts.push(`-- Rows per branch : ${rows.length}`);
  parts.push(`-- Branches        : ${branchIds.join(", ")} (the branches in the database when`);
  parts.push("--                   this file was generated; regenerate it if that changes)");
  parts.push("--");
  parts.push("-- Requires the dedicated address tables, so run the migrations that");
  parts.push("-- create them before uploading this file.");
  parts.push("--");
  parts.push("-- The file is safe to upload more than once: it empties the four");
  parts.push("-- address tables, then re-inserts them inside a single transaction.");
  parts.push("-- Ids are written explicitly because a plain VALUES list cannot read");
  parts.push("-- the id a previous statement created, and the levels point at each");
  parts.push("-- other by id.");
  parts.push("");

  parts.push("SET NAMES utf8mb4;");
  parts.push("");

  parts.push("-- Patient rows store the place name as text, not the code, so nothing");
  parts.push("-- rewrites existing patients; their saved division/district/upazila/thana");
  parts.push("-- text simply stays as it was. A patient whose text no longer matches a");
  parts.push("-- row here would fail to resolve in the cascade, so spot-check the");
  parts.push("-- Master Data reference count afterwards if you need every saved address");
  parts.push("-- to still resolve.");
  parts.push("");

  parts.push("START TRANSACTION;");
  parts.push("");

  parts.push("-- Clear the address tables, deepest first, so no foreign key is left");
  parts.push("-- pointing at a row this file is about to remove.");
  for (const category of [...ADDRESS_CATEGORY_ORDER].reverse()) {
    parts.push(`DELETE FROM \`${LOOKUP_SPECS[category].model}\`;`);
  }
  parts.push("");

  /** Ids are assigned here, deterministically, so the file is reproducible. */
  let nextId = 1;

  for (const branchId of branchIds) {
    parts.push("-- ============================================================");
    parts.push(`-- branch ${branchId}`);
    parts.push("-- ============================================================");

    /** `${category}::${code}` -> row id, so a child can resolve its parent. */
    const idByKey = new Map<string, number>();

    for (const category of ADDRESS_CATEGORY_ORDER as readonly MasterDataCategory[]) {
      const spec = LOOKUP_SPECS[category];
      const { columns, tuple } = tupleColumns(spec);
      const levelRows = rows.filter((r) => r.category === category);
      if (levelRows.length === 0) continue;

      parts.push(`-- ${spec.model}: ${levelRows.length} rows`);

      for (let i = 0; i < levelRows.length; i += ROWS_PER_INSERT) {
        const chunk = levelRows.slice(i, i + ROWS_PER_INSERT);
        const tuples = chunk.map((row) => {
          const parentId = spec.parent
            ? idByKey.get(`${spec.parent.category}::${row.parentCode ?? ""}`) ?? null
            : null;
          if (spec.parent && parentId === null) {
            // The dataset parser already rejects orphans, so this means the level
            // ordering above is wrong rather than that the data is bad.
            throw new Error(
              `Cannot emit ${category} "${row.code}": no id for ${spec.parent?.category} "${row.parentCode}"`,
            );
          }
          const id = nextId++;
          idByKey.set(`${category}::${row.code}`, id);
          return tuple(row, branchId, parentId, id);
        });
        parts.push(`INSERT INTO \`${spec.model}\``);
        parts.push(columns);
        parts.push("VALUES");
        parts.push(tuples.join(",\n") + ";");
        parts.push("");
      }
    }
  }

  parts.push("COMMIT;");
  parts.push("");

  parts.push("-- Verify: each branch should show the same per-level counts.");
  for (const category of ADDRESS_CATEGORY_ORDER) {
    const model = LOOKUP_SPECS[category].model;
    parts.push(
      `SELECT \`branchId\`, COUNT(*) AS ${model.toLowerCase()}_rows FROM \`${model}\` GROUP BY \`branchId\`;`,
    );
  }
  parts.push("");
  parts.push("-- And confirm nothing is orphaned (all four should return 0).");
  parts.push(
    "SELECT COUNT(*) AS orphan_districts FROM `District` d LEFT JOIN `Division` p ON p.id = d.divisionId WHERE p.id IS NULL;",
  );
  parts.push(
    "SELECT COUNT(*) AS orphan_upazilas FROM `Upazila` u LEFT JOIN `District` p ON p.id = u.districtId WHERE p.id IS NULL;",
  );
  parts.push(
    "SELECT COUNT(*) AS orphan_unions FROM `Union` n LEFT JOIN `Upazila` p ON p.id = n.upazilaId WHERE p.id IS NULL;",
  );
  parts.push("");

  return parts.join("\n");
}

async function main(): Promise<void> {
  const prisma = new PrismaClient();
  try {
    const branches = await prisma.branch.findMany({ select: { id: true }, orderBy: { id: "asc" } });
    if (branches.length === 0) {
      throw new Error(
        "No branches exist, so the generated file would insert nothing. " +
          "Run `npm run setup` first, or generate it against a database that has branches.",
      );
    }
    const branchIds = branches.map((b) => b.id);

    const rows = buildAddressRows();
    const byCategory = rows.reduce<Record<string, number>>((acc, r) => {
      acc[r.category] = (acc[r.category] ?? 0) + 1;
      return acc;
    }, {});

    const suffixed = rows.filter((r) => /\(\d+\)$/.test(r.label));
    console.log("Parsed from prisma/address-source:");
    for (const [category, count] of Object.entries(byCategory)) {
      console.log(`  ${category.padEnd(10)} ${count}`);
    }
    console.log(`  total      ${rows.length} per branch`);
    console.log(`  rows       ${rows.length * branchIds.length} total`);
    console.log(`  branches   ${branchIds.join(", ")} (written literally; regenerate if branches change)`);
    if (suffixed.length > 0) {
      console.log(`\nRenamed to satisfy the unique (parent, name) key: ${suffixed.length}`);
      for (const r of suffixed) console.log(`  ${r.category}  ${r.label}   (${r.code})`);
    }

    mkdirSync(join(import.meta.dirname, "..", "sql"), { recursive: true });
    writeFileSync(OUT_FILE, buildSql(rows, branchIds), "utf8");
    console.log(`\nWrote ${OUT_FILE}`);
  } finally {
    await prisma.$disconnect();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});