import { z } from "zod";

export const loginSchema = z.object({
  identifier: z
    .string({ required_error: "Email or username is required" })
    .trim()
    .min(1, "Email or username is required")
    .max(255),
  password: z
    .string({ required_error: "Password is required" })
    .min(1, "Password is required")
    .max(255),
  /** Second factor code, required once 2FA is enrolled and enabled. */
  twoFactorCode: z.string().trim().max(20).optional(),
  /** Single-use recovery code, accepted instead of twoFactorCode. */
  recoveryCode: z.string().trim().max(40).optional(),
});

// Length and character rules are enforced live against
// SecuritySetting.passwordMinLength in the service, so this only rejects empty
// payloads. Keeping a second, lower floor here would report a misleading
// "at least 4 characters" while the configured policy says 12.
const newPasswordSchema = z
  .string({ required_error: "New password is required" })
  .min(1, "New password is required")
  .max(255);

export const changePasswordSchema = z
  .object({
    currentPassword: z
      .string({ required_error: "Current password is required" })
      .min(1, "Current password is required")
      .max(255),
    newPassword: newPasswordSchema,
  })
  .refine((data) => data.currentPassword !== data.newPassword, {
    message: "New password must be different from the current password",
    path: ["newPassword"],
  });

export const adminResetPasswordSchema = z.object({
  newPassword: newPasswordSchema,
  /**
   * When true the user is flagged to choose a new password at next sign-in.
   * Defaults to true so an administrator-set password is never permanent.
   */
  requireChange: z.boolean().optional(),
});

export const twoFactorSetupSchema = z.object({
  /** The TOTP secret generated by /auth/2fa/setup, confirmed by the user. */
  code: z.string().trim().regex(/^\d{6}$/, "A 6-digit code is required"),
});

export const twoFactorDisableSchema = z.object({
  currentPassword: z.string().min(1, "Current password is required").max(255),
  code: z
    .string()
    .trim()
    .regex(/^\d{6}$/, "A 6-digit code is required")
    .optional(),
});

export const revokeSessionsSchema = z.object({
  /** Omit to revoke every session for the user, including the current one. */
  sessionId: z.number().int().positive().optional(),
});

export type LoginInput = z.infer<typeof loginSchema>;
export type ChangePasswordInput = z.infer<typeof changePasswordSchema>;
export type AdminResetPasswordInput = z.infer<typeof adminResetPasswordSchema>;
export type TwoFactorSetupInput = z.infer<typeof twoFactorSetupSchema>;
export type TwoFactorDisableInput = z.infer<typeof twoFactorDisableSchema>;
export type RevokeSessionsInput = z.infer<typeof revokeSessionsSchema>;
